package com.example.mylibrary

object Constants {
    const val QUALIFIER_ROUTER_GLOBAL = "QUALIFIER_ROUTER_GLOBAL"
    const val QUALIFIER_ROUTER_BOOKS = "QUALIFIER_ROUTER_CHANNELS"
    const val QUALIFIER_ROUTER_AUTHORS = "QUALIFIER_ROUTER_LIBRARY"
}
