package com.example.mylibrary

object Constants {
    const val QUALIFIER_ROUTER_GLOBAL = "QUALIFIER_ROUTER_GLOBAL"
    const val QUALIFIER_ROUTER_CHANNELS = "QUALIFIER_ROUTER_CHANNELS"
    const val QUALIFIER_ROUTER_LIBRARY = "QUALIFIER_ROUTER_LIBRARY"
    const val QUALIFIER_ROUTER_DONATE = "QUALIFIER_ROUTER_DONATE"
    const val QUALIFIER_ROUTER_FAVORITES = "QUALIFIER_ROUTER_FAVORITES"
    const val QUALIFIER_ROUTER_PROFILE = "QUALIFIER_ROUTER_PROFILE"
}